version: "3.3"
services:
  postgres_db:
    restart: always
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: rehdera
      POSTGRES_PASSWORD: secreta
      POSTGRES_DB: spring-test
    ports:
      - "5432:5432"

  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


